<a href="https://colab.research.google.com/github/mccoy0928/pandas_dataframe/blob/main/20230801_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 練習

In [1]:
import numpy as np

In [3]:
arr1 = np.array([
    [1, 2, 3],
    [12, 13, 15]
]) # 2x3

arr2 = np.array([
    [21, 22, 23],
    [31, 35, 40],
])

# ndarray 合并

* vstack 垂直

* hstack 水平

* 維度合并 flatten(), reshape(-1), ravel()

In [16]:
newarr = np.vstack([arr1, arr2])
print("vstack:",newarr)
newarr =np.hstack([arr1, arr2])
print("hstack:",newarr)
newarr = arr1.flatten()  # 降維度
# newarr = arr1.ravel()
print("newArray:", newarr)
# newarrAll = newarr.reshape(-1)
# print('All: ',newarrAll)


vstack: [[ 1  2  3]
 [12 13 15]
 [21 22 23]
 [31 35 40]]
hstack: [[ 1  2  3 21 22 23]
 [12 13 15 31 35 40]]
newArray: [ 1  2  3 12 13 15]


# ndarray reshape 重新塑形

In [20]:
a = np.array(range(24))
print(a, a.shape)
b = a.reshape(4,3,2)
print(b,b.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] (24,)
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]] (4, 3, 2)
