<a href="https://colab.research.google.com/github/mccoy0928/pandas_dataframe/blob/main/Numpy_try_it.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 20230805



## 建立陣列及初始值
* 我們會先import numpy 模組，透過傳入Python的list或tuple到 numpy.array() 建立陣列。

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])     #一維陣列建立
b = np.array([(2.5, 1, 3, 4.5), (5, 6, 7, 8)], dtype = float)  #二維陣列建立
c = np.array([[(2.5, 1, 3, 4.5), (5, 6, 7, 8)], [(2.5, 1, 3, 4.5), (5, 6, 7, 8)]], dtype = float)  #三維陣列建立

In [3]:
np.zeros((2, 3))               # 建立一個2x3全為0的陣列
np.ones((2, 3, 4))             # 建立一個2x3x4全為1的陣列
np.arange(1, 10, 2)            # 建立一個由1開始，不超過10，間隔值為2的均勻數值陣列
np.linspace(0, 10, 5)          # 建立一個0到10之間，均勻的5個數值陣列
np.full((3,2), 8)              # 建立一個3x2全為8的陣列
np.eye(2)                      # 建立一個5x5的單位矩陣
np.random.random((2,3))        # 建立一個2x3的隨機值矩陣

array([[0.13940543, 0.45955618, 0.05372759],
       [0.87716578, 0.68202218, 0.81623801]])

## I/O

In [4]:
original_array = np.array([1, 2, 3])
np.save('my_array', original_array)
np.savetxt('my_array.txt', original_array)
array_from_npy = np.load('my_array.npy')
print(array_from_npy)

array_from_txtfile = np.loadtxt('my_array.txt')
print(array_from_txtfile)


[1 2 3]
[1. 2. 3.]


## Data Types
* NumPy支援比Python更多的數字類型。可參考下圖。
[caption id=”attachment_19" align=”alignnone” width=”866"]

* 其中有5種基本數字類型比較常用，分別是booleans (bool), integers (int), unsigned integers (uint), floating point (float)和complex。

In [6]:
np.array([1.2, 3, 5.2], dtype='i')

np.array([1, 2, 3], dtype='f')

x = np.float32(1)
x

y = np.int_([1.0, 2.3])
y

array([1, 2])

* Inspecting Your Array

In [7]:
a = np.array([1, 2, 3])
b = np.array([(2.5, 1, 4.5), (5, 6, 7, 8)])
a.shape                        # Array dimensions

len(a)                         # Length of array

len(b)                         # Length of array

b.ndim                         # Number of array dimensions

a.size                         # Number of array elements

b.size                         # Number of array elements

b.dtype                        # Data type of array elements

a.dtype                        # Data type of array elements

b.dtype.name                   # Name of data type

a.dtype.name                   # Name of data type

a.astype(float)                # Convert an array to a different type


<ipython-input-7-730634e3bfe0>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b = np.array([(2.5, 1, 4.5), (5, 6, 7, 8)])


array([1., 2., 3.])

* Array Mathematics

In [8]:
a = np.array([1, 2, 3])
b = np.array([2, 4, 6])
np.add(a, b)                   # 陣列加法，也可以a + b

np.subtract(a, b)              # 陣列減法，也可以a – b

np.multiply(a, b)              # 陣列乘法，也可以a * b

np.divide(a, b)                # 陣列除法，也可以a / b

# 除了四則運算之外，也可以對陣列做其他的算術運算
c = np.array([1, 4, 9])
np.sqrt(c)

np.sin(c)

np.cos(c)

np.log(c)


array([0.        , 1.38629436, 2.19722458])

# Comparison
* NumPy也提供Array幾種比較方式如下：

In [9]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.array([(1, 3, 3), (4, 7, 6)])
c = np.array([(1, 2, 3), (4, 5, 6)])
a == b                         # Element-wise comparison

a < 3                          # Element-wise comparison

np.array_equal(a, b)           # Array-wise comparison


False

# Aggregate Functions
* 利用numpy的聚合函數(Aggregate Functions)於統計領域是很方便的，常見聚合函數有最大值(max)、最小值(min)、中位數( median)、平均數(mean)、方差、標準差(std)、在numpy的使用上是很常見的。

# Copying & Sorting Arrays
* numpy同時提供多種陣列間的copying及sorting功能，我們就先簡介其中幾種做法。

In [10]:
a = np.array([5, 13, -5, -2, 3, 4, 7])
a.sort()
a
# array([-5, -2, 3, 4, 5, 7, 13])
b = np.copy(a)
b
# array([-5, -2, 3, 4, 5, 7, 13])

array([-5, -2,  3,  4,  5,  7, 13])

# Subsetting, Slicing, Indexing
* 藉由下列範例你將會清楚了解Subsetting, Slicing及Indexing的應用。我們先試著各建立一個一維陣列(1D array)及二維陣列(2D array)如下：

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([(2.5, 1, 3, 4.5), (5, 6, 7, 8)])

In [13]:
# Subsetting
a[2]
b[1,3]

8.0

In [14]:
# Slicing
a[0:2]
b[0 : 2, 1]

array([1., 6.])

In [15]:
b[1, 0 : 2]

array([5., 6.])

In [16]:
# Boolean Indexing
a[a<4]

array([1, 2, 3])

In [19]:
# Transposing Array
a = np.array([(1, 3, 5, 7), (2, 4, 6, 8)])
b = np.transpose(a)
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
print(b.T)

[[1 3 5 7]
 [2 4 6 8]]


In [22]:
# Adding/Removing Elements
a = np.array([1, 2, 3, 4])     # 建立a陣列
b = np.array([6, 7, 8, 9])
np.append(a, 5)

array([1, 2, 3, 4, 5])

In [23]:
np.insert(a, 1, 0)

array([1, 0, 2, 3, 4])

In [24]:
np.delete(b, [2])

array([6, 7, 9])

In [26]:
a.resize((2,2))
a

array([[1, 2],
       [3, 4]])

* Combining Arrays
利用NumPy將array間做彼此合併或連結的方法很多，這裡先簡單介紹一些常用的方式。
* vstack：垂直方向合併
* hstack：水平方向合併

In [27]:
a = np.array([(1, 2), (3, 4)])
b = np.array([(5, 6), (7, 8)])
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [28]:
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [29]:
#concatenate (axis = 0)：沿垂直方向合併
#concatenate (axis = 1)：沿水平方向合併
np.concatenate((a, b), axis = 0)   # axis=0，沿垂直方向合併
np.concatenate((a, b), axis = 1)   # axis=1，沿水平方向合併

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# Splitting Arrays
* 跟Combining Arrays一樣，NumPy提供一些在不同軸向的切割方式，如下說明：
* vsplit：垂直方向分割
* hsplit：水平方向分割

In [30]:
a = np.array([(1, 2, 3, 4, 5, 6), (-1, -2, -3, -4, -5, -6), (2, 4, 6, 8, 10, 12)])
a
np.vsplit(a, 3)                # 垂直方向分割
#[array([[1, 2, 3, 4, 5, 6]]), array([[-1, -2, -3, -4, -5, -6]]), array([[ 2, 4, 6, 8, 10, 12]])]
np.hsplit(a, 2)                # 水平方向分割
# [array([[ 1, 2, 3],
#  [-1, -2, -3],
#  [ 2, 4, 6]]), array([[ 4, 5, 6],
#  [-4, -5, -6],
#  [ 8, 10, 12]])]
np.split(a, 3, axis=0)         # axis=0，沿垂直方向分割
# [array([[1, 2, 3, 4, 5, 6]]), array([[-1, -2, -3, -4, -5, -6]]), array([[ 2, 4, 6, 8, 10, 12]])]
np.split(a, 2, axis=1)         # axis=1，沿水平方向分割


[array([[ 1,  2,  3],
        [-1, -2, -3],
        [ 2,  4,  6]]),
 array([[ 4,  5,  6],
        [-4, -5, -6],
        [ 8, 10, 12]])]